### ISSUE TITLE
Feature: Add Group function to group factories by "prestation"

### ISSUE THREAD

**Issue by ChabbehAymen** [AyoubyAmazu/prefact#24]
## Feature : Add "prestation" grouping functionality

**Description:**
When clicking on the prestation tab for each table should group all of it's item by it's prestation and adds a row blow each group with check box and total, and when checking the checkbox all the items of the group should be checked

**How it should work:**
- Adding a click listener on the prestation tab that calls the function of grouping
- Collect rows that have the same prestation value in groups
- Add a row bellow each group with a checkbox that relate to all of the group items, also with total of items values displayed in the table
- Checking the group row box will also check all the related items check-boxes

**How it should be done:**
- Create a branch with the feature name from the main branch
- Work in the branch edit, test, push
- When It's done create pull request

**Comment by Sakany-org** [comment]
**Final result should be something like this :**
![Screenshot_20241203_215120](https://github.com/user-attachments/assets/04b23ef3-d0fd-4474-91be-2a536ba93fdd)
